Refactor branch name validation logic

diff --git a/.github/workflows/branch-name-validation.yml b/.github/workflows/branch-name-validation.yml
--- a/.github/workflows/branch-name-validation.yml
+++ b/.github/workflows/branch-name-validation.yml
@@ -86,21 +86,28 @@ jobs:
           targeted_regex='^(dev|fix)/[a-z0-9-]+-v[1-9][0-9]?\.(0|[1-9][0-9]?)\.0$'
           contributor_regex='^([a-z]+/)?[a-z0-9-]+$'
 
-          if [[ "$BASE_REF" == "main" ]]; then
-            if [[ ! "$HEAD_REF" =~ $version_regex ]]; then
-              echo "Invalid branch name: $HEAD_REF."
-              echo "Branch targets main but does not have a name with the required"
-              echo "form vM.m.0. Example valid names are v1.2.0, v12.3.0, and v2.0.0,"
+          if [[ "$HEAD_REF" =~ $version_regex ]]; then
+            if [[ ! "$BASE_REF" == "main" ]]; then
+              echo "Invalid branch: $HEAD_REF."
+              echo "The base branch for a version branch must be main"
+              echo "and not $BASE_REF."
+              
               exit 1
             fi
-          elif [[ "$BASE_REF" =~ $version_regex ]]; then
-            if [[ ! "$HEAD_REF" =~ $targeted_regex ]]; then
-              echo "Invalid branch name: $HEAD_REF."
-              echo "Branch targets a version branch but does not have a valid targeted"
-              echo "branch name. Example valid names are fix/seg-fault-v12.3.0"
-              echo "and dev/memory-management-v1.2.0."
+
+          elif [[ "$HEAD_REF" =~ $targeted_regex ]]; then
+            if [[ ! "$BASE_REF" =~ $version_regex ]]; then
+              echo "Invalid branch: $HEAD_REF."
+              echo "The base branch for a targeted branch must be a version branch"
+              echo "and not $BASE_REF."
               exit 1
-            fi 
+            else [[ ! <version-suffix of $HEAD_REF> == $VASE_REF ]]; then
+              echo "Invalid branch: $HEAD_REF."
+              echo "The base branch for a targeted branch must have the same version,"
+              echo "but base branch name is $BASE_REF."
+              exit 1
+            fi
+            
           elif [[ "$HEAD_REF" == "main" ]]; then
             echo "Invalid branch name: main. A contributor branch cannot be main."
             exit 1
@@ -121,7 +128,7 @@ jobs:
             fi
           else
             if [[ ! "$BASE_REF" =~ $targeted_regex ]] &&
-               [[ ! "$HEAD_REF" =~ $contributor_regex ]]; then
+               [[ ! "$BASE_REF" =~ $contributor_regex ]]; then
               echo "Invalid branch: $HEAD_REF."
               echo "A contributor branch must target a targeted branch or a"
               echo "contributor branch."
