Update branch-name-validation.yml

diff --git a/.github/workflows/branch-name-validation.yml b/.github/workflows/branch-name-validation.yml
--- a/.github/workflows/branch-name-validation.yml
+++ b/.github/workflows/branch-name-validation.yml
@@ -10,46 +10,47 @@ name: Defines Branch Names Validation and Branch Workflow
 # Validate pull request branch names against repository branch rules
 # for the following four kinds of branches:
 #
-# The 'main' branch (protected).
+# 1. The 'main' branch (protected).
 #
-# A 'version' branch (protected, based on the main branch, created by
-# an approver) with branch name in the form:
+# 2, A 'version' branch (protected, based on the main branch, created by
+#    an approver) with branch name in the form:
 #
-#   vM.m.0
+#      v<M>.<m>.0
 #
-# where:
+#    where:
 #
-#   M is 1-2 digits starting with 1-9.
-#   m is either 0 or 1-2 digits starting with 1-9.
+#      <M> is 1-2 digits starting with 1-9.
+#      <m> is either 0 or 1-2 digits starting with 1-9.
 #
-# A 'targeted' branch (not protected, based on a version branch) with
-# a branch name in one of the forms:
+# 3, A 'targeted' branch (not protected, based on a version branch) with
+#    a branch name in one of the forms:
 #
-#   dev/<short-name>-<target-version>
-#   fix/<short-name>-<target-version>
+#      dev/<description>-<target-version>
+#      fix/<description>-<target-version>
 #
-# where:
-#   <short-name> is a brief lowercase descriptor using letters,
-#   numbers, and hyphens.
+#    where:
 #
-#   <target-version> is the name of the 'version' branch.
+#      <description> consists of lowercase letters, digits, and hyphens.
+#      <target-version> is the name of the 'version' branch.
 #
-# A 'contributor' branch (not protected, not based on 'main' or a
-# 'version' branch) with a branch name in the form:
+# 4, A 'contributor' branch (not protected, not based on 'main' or a
+#    'version' branch) with a branch name (other than 'main') in the form:
 #
-#   [<type>/]<short-name>
+#       [<type>/]<description>
 #
-#  where <type> is a lowercase word using only letters, for example,
-#  'dev', 'fix', or 'mywork'.
+#     where <type> consists of lowercase letters )for example, 'dev', 'fix',
+#     or 'mywork') and <description> is as defined above.
 #
 # Protected branches:
+#
 # - Require pull request before merging
 # - Require approvals (1+)
 # - Require status checks
 # - Block force pushes
 # - Block deletions
 #
-# This workflow mirrors the branch-naming policy used by scripts/bin/mkbranch.
+# This workflow mirrors the branch-naming policy used by
+# <repo>/scripts/bin/mkbranch.
 # 
 # For more information, see '<repo>/docs/md/Contributor_Guide.md'.
 #
@@ -70,11 +71,11 @@ permissions:
   contents: read
 
 jobs:
-  validate-branch-name:
-    name: Validate branch name
+  validate-branch:
+    name: Validate branch
     runs-on: ubuntu-latest
     steps:
-      - name: Check branch name rules
+      - name: Check branch rules
         shell: bash
         env:
           BASE_REF: ${{ github.base_ref }}
@@ -86,53 +87,48 @@ jobs:
           targeted_regex='^(dev|fix)/[a-z0-9-]+-v[1-9][0-9]?\.(0|[1-9][0-9]?)\.0$'
           contributor_regex='^([a-z]+/)?[a-z0-9-]+$'
 
-          if [[ "$HEAD_REF" =~ $version_regex ]]; then
+          # 1. '=main' branch'?
+          if [[ "$HEAD_REF" == "main" ]]; then
+            echo "Invalid pull request: pulling to main is not allowed."
+            exit 1
+            
+          # 2. '=ersion' branch'?
+          elif [[ "$HEAD_REF" =~ $version_regex ]]; then
             if [[ "$BASE_REF" != "main" ]]; then
-              echo "Invalid branch: $HEAD_REF."
-              echo "The base branch for a version branch must be main"
-              echo "and not $BASE_REF."
-              
+              echo "Invalid pull request: version branch $HEAD_REF must only pull"
+              echo "from main and not from $BASE_REF."
               exit 1
             fi
+            # TODO: verify user is an approver.
 
+          # 3, 'targeted' branch'?
           elif [[ "$HEAD_REF" =~ $targeted_regex ]]; then
             if [[ ! "$BASE_REF" =~ $version_regex ]]; then
-              echo "Invalid branch: $HEAD_REF."
-              echo "The base branch for a targeted branch must be a version branch"
-              echo "and not $BASE_REF."
+              echo "Invalid pull request: targeted branch $HEAD_REF"
+              echo "must only pull from a version branch and not $BASE_REF."
               exit 1
             elif [[ "${HEAD_REF##*-}" != "$BASE_REF" ]]; then
-              echo "Invalid branch: $HEAD_REF."
-             echo "A targeted branch must target the version branch named in its suffix."
-              echo "Expected base branch: ${HEAD_REF##*-}; actual base branch: $BASE_REF."
+              echo "Invalid pull request: targeted branch $HEAD_REF"
+              echo "must only pull from the version branch named in its suffix"
+              echo "${HEAD_REF##*-} and not from $BASE_REF."
               exit 1
             fi
+            # TODO: verify user is a approver.
 
+          # 4. 'contributor' branch'?
           elif [[ "$HEAD_REF" =~ $contributor_regex ]]; then
             if [[ ! "$BASE_REF" =~ $targeted_regex ]] &&
                [[ ! "$BASE_REF" =~ $contributor_regex ]]; then
-              echo "Invalid branch: $HEAD_REF."
-              echo "A contributor branch must target a targeted branch or a"
-              echo "contributor branch."
+              echo "Invalid pull request: contributor branch $HEAD_REF."
+              echo "must only pull from a targeted or contributor branch and not"
+              echo "from $BASE_REF."
               exit 1
-
-            elif [[ "$HEAD_REF" == "main" ]]; then
-              echo "Invalid branch name: main. A contributor branch cannot be main."
-              exit 1
-            else
-              echo "Invalid branch name: $HEAD_REF."
-              echo "Name must be a contributor branch name."
-              exit 1
-            fi
+            # TODO: verify user is a contributor.
 
           else
-            if [[ ! "$BASE_REF" =~ $targeted_regex ]] &&
-               [[ ! "$BASE_REF" =~ $contributor_regex ]]; then
-              echo "Invalid branch: $HEAD_REF."
-              echo "A contributor branch must target a targeted branch or a"
-              echo "contributor branch."
-              exit 1
-            fi
+            echo "Invalid pull request: $HEAD_REF"
+            echo "is an unexpected name for a pulling branch."
+            exit 1
           fi
 
-          echo "Valid branch name: $HEAD_REF (target: $BASE_REF)."
+          echo "Valid pull request from $BASE_REF to $HEAD_REF)."
